[package]
name = "vdex"
version = "0.1.0"
authors = ["Chris McKinney <ntd5@tachibanatech.com>"]
edition = "2018"

[dependencies]
bitflags = "1"
csv = "1"
enum-repr = { path = "enum-repr" }
rand = "0.6"
veekun = { path = "veekun" }
